### ISSUE TITLE
스터디 1주차 과제 제출란 (여기에 해주세요)

### ISSUE THREAD

**Issue by etilelab** [etilelab/WebCrawlingStudy#11]
덧글로 소스코드를 **zip파일**로 압축하여 첨부해주시기 바랍니다.
제출 마감일은 **9월 30일 토요일 오후 9시까지** 입니다.

이미 다른 이슈를 통해 제출하신분은 재제출하실 필요없습니다.

**Comment by kimyoungchae** [comment]
[week1_exam.zip](https://github.com/etilelab/webcrawling/files/1332931/week1_exam.zip)
과제 제출합니다.
좀더 완전하게 하고 싶지만 실력이 아직 없어서,
마지막까지 과제만 마스터하면 기본기는 충분히 갖출수 있을거라고 생각하고  
조급하지 않게 꾸준히  가겠습니다.

**Comment by namsoojang** [comment]
[week1_jangnamsoo.zip](https://github.com/etilelab/webcrawling/files/1333292/week1_jangnamsoo.zip)

제출합니다. 
처음에 아무리 해도 크롤링을 할 수가 없어서 엄청 고생했네요... 
이 함수 저 함수 바꿔하다가 find 가 아닌 select 를 사용하여 진행하였습니다. (문제는 함수가 아니였지만..)
 표에서 숨겨진 속성이 있을 경우   크롬-검사로 html 을 확인하여 나타나는 부분과
다른 부분이 있다는 것을 처음 알았네요... 고맙습니다 ㅎ

**Comment by fdlf5518** [comment]
소스코드 제출합니다.
[week1.zip](https://github.com/etilelab/webcrawling/files/1336742/week1.zip)

**Comment by DunMorogh** [comment]
[과제_1주차.zip](https://github.com/etilelab/webcrawling/files/1337464/_1.zip)

제출합니다.

**Comment by sesalam88** [comment]
[WEEK01 practice.zip](https://github.com/etilelab/webcrawling/files/1338066/WEEK01.practice.zip)
제출합니다~ 크롤링은 처음이라 너무 재미있었습니다.

**Comment by myzin** [comment]
과제 제출합니다.
[1_week.zip](https://github.com/etilelab/webcrawling/files/1342715/1_week.zip)

**Comment by dbsxo2995** [comment]
[crawlingPC.zip](https://github.com/etilelab/webcrawling/files/1344350/crawlingPC.zip)
과제 제출합니당

**Comment by 2DayLab** [comment]
[week1.py.zip](https://github.com/etilelab/webcrawling/files/1346384/week1.py.zip)

코딩은 처음이라 제대로 한건지 모르겠습니다

**Comment by Dawon94** [comment]
과제제출합니다. 
[Assignment1.zip](https://github.com/etilelab/webcrawling/files/1346931/Assignment1.zip)

**Comment by saintb** [comment]
[1주차과제.zip](https://github.com/etilelab/webcrawling/files/1361598/1.zip)
