### ISSUE TITLE
안녕하세요 열심히하겠습니다.

### ISSUE THREAD

**Issue by sesalam88** [etilelab/WebCrawlingStudy#16]
너무 나도 좋은 스터디 그룹에 들어오게 되서 너무 감사합니다.
비록 파이썬에 입문한지는 얼마 안됬지만 죽을 각오로 열심히 배우겠습니다. 
카톡: over4455  입니다.

**Comment by etilelab** [comment]
스터디 카카오톡 톡방에 접속해있는 닉네임을 알려주시기 바랍니다
