### ISSUE TITLE
스터디 2주차 과제 제출란(마감기간 연장)

### ISSUE THREAD

**Issue by etilelab** [etilelab/WebCrawlingStudy#26]
스터디 2주차 과제 제출란입니다.
2주차 과제제출 마감일은 시험기간과 겹쳐서 기존 **10월 15일(일요일 오후 11시 50분)에서** **10월 29일(일요일 오후 11시 50분)까지**
제출해주시면 되겠습니다. 시험에 전념하시기 바랍니다.
과제다운로드 : https://github.com/etilelab/webcrawling/blob/master/Study/Week2/practice02.pdf
과제문제 해설 : https://www.youtube.com/watch?v=tVbEKr40VyA&feature=youtu.be

**Comment by namsoojang** [comment]
[과제2주차_장남수.zip](https://github.com/etilelab/webcrawling/files/1384841/2._.zip)

인터페이스 및 조건들은 제가 임의로 수정해서 만들었습니다. 
만족스럽지는 않지만 더 잡고 있으면 끝이 없을 것 같아서 이만 제출합니다.

**Comment by HwangJaeSang** [comment]
[2주차_황재상.zip](https://github.com/etilelab/webcrawling/files/1409676/2._.zip)

**Comment by sesalam88** [comment]
파이썬 기초가 부족해서 완성하는데 너무오래 걸렸네요 황재상님과 장남수님의 코드가 많은 도움이 됬습니다. 감사합니다. 숙제를 통해 많은 것을 배우는것 같습니다. 이제 드디어 Selenium을 배울수 있게 되서 너무 기대가 되네요 
[숙제-신영국.zip](https://github.com/etilelab/webcrawling/files/1427431/-.zip)
