### ISSUE TITLE
1주차 크롤링과제

### ISSUE THREAD

**Issue by HwangJaeSang** [etilelab/WebCrawlingStudy#3]
[testCrawling.zip](https://github.com/etilelab/webcrawling/files/1368572/testCrawling.zip)

**Comment by etilelab** [comment]
소스코드 파일 자체를 드래그앤 드랍해주시면 감사하겠습니다! 띄어쓰기가 모두 깨지어 확인이 불가하네요 ㅠ_ㅠ

**Comment by HwangJaeSang** [comment]
소스트리를 다운받았는데 이건 파일 업다운로드만 되는건가여?? 이렇게 issues에는 안되구?

**Comment by etilelab** [comment]
소스트리에서 이슈 기능은 보지 못한것 같습니다
