### ISSUE TITLE
반갑습니다.

### ISSUE THREAD

**Issue by DunMorogh** [etilelab/WebCrawlingStudy#9]
때마침 크롤링 관련하여 검색하다가 에틸랩님 블로그가 설명이 제일 잘돼있어서 참여하게 되었습니다.
그런데 처음에 올리셨던 포스트는 지우셨나봐요 ;; 
여기저기 막 검색해가며 배우는 중인데 강의에도 열심히 참여하겠습니다~

**Comment by etilelab** [comment]
구 크롤링 강의는 새로히 업데이트하면서 삭제되었습니다. 반갑습니다

**Comment by etilelab** [comment]
카카오톡 스터디 오픈채팅방에 있는 닉네임을 알려주시기 바랍니다!
